-- Script SQL untuk membuat tabel userguru
-- Jalankan script ini di SQL Editor Supabase Anda.

-- Membuat tabel userguru jika belum ada
CREATE TABLE IF NOT EXISTS public.userguru (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    email text not null,
    password text not null
);

-- Tambahkan constraint UNIQUE pada email jika belum ada
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'userguru_email_key'
    ) THEN
        ALTER TABLE public.userguru ADD CONSTRAINT userguru_email_key UNIQUE (email);
    END IF;
END $$;

-- Mengaktifkan Row Level Security (RLS) pada tabel userguru
ALTER TABLE public.userguru ENABLE ROW LEVEL SECURITY;

-- Hapus policy lama jika ada untuk menghindari error
DROP POLICY IF EXISTS "Allow public read access to userguru" ON public.userguru;

-- Membuat policy agar public bisa membaca data userguru (untuk keperluan login)
CREATE POLICY "Allow public read access to userguru" ON public.userguru
    FOR SELECT USING (true);

-- Insert data guru default (jika belum ada)
INSERT INTO public.userguru (email, password)
SELECT 'guru@smppgri.sch.id', 'admin123'
WHERE NOT EXISTS (
    SELECT 1 FROM public.userguru WHERE email = 'guru@smppgri.sch.id'
);
